In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.model_selection import train_test_split
from k_means import KMeans
from sklearn.metrics import silhouette_score

**Exploration des données,vérification des valeurs manquantes,dupliquées,etc**

In [2]:
data = pd.read_csv("Mall_Customers.csv")
data.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [4]:
data.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(0)

**Encodage des variables catégorielles**

In [6]:
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])
data

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1       1   19                  15                      39
1             2       1   21                  15                      81
2             3       0   20                  16                       6
3             4       0   23                  16                      77
4             5       0   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196       0   35                 120                      79
196         197       0   45                 126                      28
197         198       1   32                 126                      74
198         199       1   32                 137                      18
199         200       1   30                 137                      83

[200 rows x 5 columns]

**Mise à l'échelle des variables numériques**

In [7]:
scaler = StandardScaler()
data = data.drop('CustomerID', axis=1)
X = scaler.fit_transform(data)
X

array([[ 1.12815215, -1.42456879, -1.73899919, -0.43480148],
       [ 1.12815215, -1.28103541, -1.73899919,  1.19570407],
       [-0.88640526, -1.3528021 , -1.70082976, -1.71591298],
       [-0.88640526, -1.13750203, -1.70082976,  1.04041783],
       [-0.88640526, -0.56336851, -1.66266033, -0.39597992],
       [-0.88640526, -1.20926872, -1.66266033,  1.00159627],
       [-0.88640526, -0.27630176, -1.62449091, -1.71591298],
       [-0.88640526, -1.13750203, -1.62449091,  1.70038436],
       [ 1.12815215,  1.80493225, -1.58632148, -1.83237767],
       [-0.88640526, -0.6351352 , -1.58632148,  0.84631002],
       [ 1.12815215,  2.02023231, -1.58632148, -1.4053405 ],
       [-0.88640526, -0.27630176, -1.58632148,  1.89449216],
       [-0.88640526,  1.37433211, -1.54815205, -1.36651894],
       [-0.88640526, -1.06573534, -1.54815205,  1.04041783],
       [ 1.12815215, -0.13276838, -1.54815205, -1.44416206],
       [ 1.12815215, -1.20926872, -1.54815205,  1.11806095],
       [-0.88640526, -0.27630176, -1.50998262, -0.59008772],
       [ 1.12815215, -1.3528021 , -1.50998262,  0.61338066],
       [ 1.12815215,  0.94373197, -1.43364376, -0.82301709],
       [-0.88640526, -0.27630176, -1.43364376,  1.8556706 ],
       [ 1.12815215, -0.27630176, -1.39547433, -0.59008772],
       [ 1.12815215, -0.99396865, -1.39547433,  0.88513158],
       [-0.88640526,  0.51313183, -1.3573049 , -1.75473454],
       [ 1.12815215, -0.56336851, -1.3573049 ,  0.88513158],
       [-0.88640526,  1.08726535, -1.24279661, -1.4053405 ],
       [ 1.12815215, -0.70690189, -1.24279661,  1.23452563],
       [-0.88640526,  0.44136514, -1.24279661, -0.7065524 ],
       [ 1.12815215, -0.27630176, -1.24279661,  0.41927286],
       [-0.88640526,  0.08253169, -1.20462718, -0.74537397],
       [-0.88640526, -1.13750203, -1.20462718,  1.42863343],
       [ 1.12815215,  1.51786549, -1.16645776, -1.7935561 ],
       [-0.88640526, -1.28103541, -1.16645776,  0.88513158],
       [ 1.12815215,  1.01549866, -1.05194947, -1.7935561 ],
       [ 1.12815215, -1.49633548, -1.05194947,  1.62274124],
       [-0.88640526,  0.7284319 , -1.05194947, -1.4053405 ],
       [-0.88640526, -1.28103541, -1.05194947,  1.19570407],
       [-0.88640526,  0.22606507, -1.01378004, -1.28887582],
       [-0.88640526, -0.6351352 , -1.01378004,  0.88513158],
       [-0.88640526, -0.20453507, -0.89927175, -0.93948177],
       [-0.88640526, -1.3528021 , -0.89927175,  0.96277471],
       [-0.88640526,  1.87669894, -0.86110232, -0.59008772],
       [ 1.12815215, -1.06573534, -0.86110232,  1.62274124],
       [ 1.12815215,  0.65666521, -0.82293289, -0.55126616],
       [-0.88640526, -0.56336851, -0.82293289,  0.41927286],
       [-0.88640526,  0.7284319 , -0.82293289, -0.86183865],
       [-0.88640526, -1.06573534, -0.82293289,  0.5745591 ],
       [-0.88640526,  0.80019859, -0.78476346,  0.18634349],
       [-0.88640526, -0.85043527, -0.78476346, -0.12422899],
       [-0.88640526, -0.70690189, -0.78476346, -0.3183368 ],
       [-0.88640526, -0.56336851, -0.78476346, -0.3183368 ],
       [-0.88640526,  0.7284319 , -0.70842461,  0.06987881],
       [ 1.12815215, -0.41983513, -0.70842461,  0.38045129],
       [-0.88640526, -0.56336851, -0.67025518,  0.14752193],
       [ 1.12815215,  1.4460988 , -0.67025518,  0.38045129],
       [-0.88640526,  0.80019859, -0.67025518, -0.20187212],
       [ 1.12815215,  0.58489852, -0.67025518, -0.35715836],
       [-0.88640526,  0.87196528, -0.63208575, -0.00776431],
       [ 1.12815215,  2.16376569, -0.63208575, -0.16305055],
       [-0.88640526, -0.85043527, -0.55574689,  0.03105725],
       [ 1.12815215,  1.01549866, -0.55574689, -0.16305055],
       [ 1.12815215,  2.23553238, -0.55574689,  0.22516505],
       [ 1.12815215, -1.42456879, -0.55574689,  0.18634349],
       [-0.88640526,  2.02023231, -0.51757746,  0.06987881],
       [-0.88640526,  1.08726535, -0.51757746,  0.34162973],
       [ 1.12815215,  1.73316556, -0.47940803,  0.03105725],
       [ 1.12815215, -1.49633548, -0.47940803,  0.34162973],
       [-0.88640526,  0.29783176, -0.47940803, -0.00776431],
       [-0.88640526,  2.091999  , -0.47940803, -0.08540743],
       [ 1.12815215, -1.42456879, -0.47940803,  0.34162973],
       [-0.88640526, -0.49160182, -0.47940803, -0.12422899],
       [ 1.12815215,  2.23553238, -0.4412386 ,  0.18634349],
       [-0.88640526,  0.58489852, -0.4412386 , -0.3183368 ],
       [-0.88640526,  1.51786549, -0.40306917, -0.04658587],
       [-0.88640526,  1.51786549, -0.40306917,  0.22516505],
       [ 1.12815215,  1.4460988 , -0.25039146, -0.12422899],
       [ 1.12815215, -0.92220196, -0.25039146,  0.14752193],
       [-0.88640526,  0.44136514, -0.25039146,  0.10870037],
       [ 1.12815215,  0.08253169, -0.25039146, -0.08540743],
       [-0.88640526, -1.13750203, -0.25039146,  0.06987881],
       [-0.88640526,  0.7284319 , -0.25039146, -0.3183368 ],
       [ 1.12815215,  1.30256542, -0.25039146,  0.03105725],
       [ 1.12815215, -0.06100169, -0.25039146,  0.18634349],
       [ 1.12815215,  2.02023231, -0.25039146, -0.35715836],
       [-0.88640526,  0.51313183, -0.25039146, -0.24069368],
       [-0.88640526, -1.28103541, -0.25039146,  0.26398661],
       [ 1.12815215,  0.65666521, -0.25039146, -0.16305055],
       [-0.88640526,  1.15903204, -0.13588317,  0.30280817],
       [-0.88640526, -1.20926872, -0.13588317,  0.18634349],
       [-0.88640526, -0.34806844, -0.09771374,  0.38045129],
       [-0.88640526,  0.80019859, -0.09771374, -0.16305055],
       [-0.88640526,  2.091999  , -0.05954431,  0.18634349],
       [ 1.12815215, -1.49633548, -0.05954431, -0.35715836],
       [ 1.12815215,  0.65666521, -0.02137488, -0.04658587],
       [-0.88640526,  0.08253169, -0.02137488, -0.39597992],
       [-0.88640526, -0.49160182, -0.02137488, -0.3183368 ],
       [ 1.12815215, -1.06573534, -0.02137488,  0.06987881],
       [-0.88640526,  0.58489852, -0.02137488, -0.12422899],
       [-0.88640526, -0.85043527, -0.02137488, -0.00776431],
       [ 1.12815215,  0.65666521,  0.01679455, -0.3183368 ],
       [ 1.12815215, -1.3528021 ,  0.01679455, -0.04658587],
       [-0.88640526, -1.13750203,  0.05496398, -0.35715836],
       [-0.88640526,  0.7284319 ,  0.05496398, -0.08540743],
       [ 1.12815215,  2.02023231,  0.05496398,  0.34162973],
       [ 1.12815215, -0.92220196,  0.05496398,  0.18634349],
       [ 1.12815215,  0.7284319 ,  0.05496398,  0.22516505],
       [-0.88640526, -1.28103541,  0.05496398, -0.3183368 ],
       [-0.88640526,  1.94846562,  0.09313341, -0.00776431],
       [ 1.12815215,  1.08726535,  0.09313341, -0.16305055],
       [ 1.12815215,  2.091999  ,  0.09313341, -0.27951524],
       [ 1.12815215,  1.94846562,  0.09313341, -0.08540743],
       [ 1.12815215,  1.87669894,  0.09313341,  0.06987881],
       [-0.88640526, -1.42456879,  0.09313341,  0.14752193],
       [-0.88640526, -0.06100169,  0.13130284, -0.3183368 ],
       [ 1.12815215, -1.42456879,  0.13130284, -0.16305055],
       [-0.88640526, -1.49633548,  0.16947227, -0.08540743],
       [-0.88640526, -1.42456879,  0.16947227, -0.00776431],
       [-0.88640526,  1.73316556,  0.16947227, -0.27951524],
       [-0.88640526,  0.7284319 ,  0.16947227,  0.34162973],
       [-0.88640526,  0.87196528,  0.24581112, -0.27951524],
       [-0.88640526,  0.80019859,  0.24581112,  0.26398661],
       [ 1.12815215, -0.85043527,  0.24581112,  0.22516505],
       [-0.88640526, -0.06100169,  0.24581112, -0.39597992],
       [-0.88640526,  0.08253169,  0.32214998,  0.30280817],
       [ 1.12815215,  0.010765  ,  0.32214998,  1.58391968],
       [-0.88640526, -1.13750203,  0.36031941, -0.82301709],
       [-0.88640526, -0.56336851,  0.36031941,  1.04041783],
       [ 1.12815215,  0.29783176,  0.39848884, -0.59008772],
       [ 1.12815215,  0.08253169,  0.39848884,  1.73920592],
       [ 1.12815215,  1.4460988 ,  0.39848884, -1.52180518],
       [ 1.12815215, -0.06100169,  0.39848884,  0.96277471],
       [ 1.12815215,  0.58489852,  0.39848884, -1.5994483 ],
       [ 1.12815215,  0.010765  ,  0.39848884,  0.96277471],
       [-0.88640526, -0.99396865,  0.43665827, -0.62890928],
       [-0.88640526, -0.56336851,  0.43665827,  0.80748846],
       [ 1.12815215, -1.3528021 ,  0.4748277 , -1.75473454],
       [-0.88640526, -0.70690189,  0.4748277 ,  1.46745499],
       [-0.88640526,  0.36959845,  0.4748277 , -1.67709142],
       [ 1.12815215, -0.49160182,  0.4748277 ,  0.88513158],
       [ 1.12815215, -1.42456879,  0.51299713, -1.56062674],
       [-0.88640526, -0.27630176,  0.51299713,  0.84631002],
       [-0.88640526,  1.30256542,  0.55116656, -1.75473454],
       [ 1.12815215, -0.49160182,  0.55116656,  1.6615628 ],
       [-0.88640526, -0.77866858,  0.58933599, -0.39597992],
       [-0.88640526, -0.49160182,  0.58933599,  1.42863343],
       [ 1.12815215, -0.99396865,  0.62750542, -1.48298362],
       [ 1.12815215, -0.77866858,  0.62750542,  1.81684904],
       [ 1.12815215,  0.65666521,  0.62750542, -0.55126616],
       [-0.88640526, -0.49160182,  0.62750542,  0.92395314],
       [-0.88640526, -0.34806844,  0.66567484, -1.09476801],
       [ 1.12815215, -0.34806844,  0.66567484,  1.54509812],
       [ 1.12815215,  0.29783176,  0.66567484, -1.28887582],
       [ 1.12815215,  0.010765  ,  0.66567484,  1.46745499],
       [-0.88640526,  0.36959845,  0.66567484, -1.17241113],
       [-0.88640526, -0.06100169,  0.66567484,  1.00159627],
       [-0.88640526,  0.58489852,  0.66567484, -1.32769738],
       [-0.88640526, -0.85043527,  0.66567484,  1.50627656],
       [ 1.12815215, -0.13276838,  0.66567484, -1.91002079],
       [-0.88640526, -0.6351352 ,  0.66567484,  1.07923939],
       [ 1.12815215, -0.34806844,  0.66567484, -1.91002079],
       [-0.88640526, -0.6351352 ,  0.66567484,  0.88513158],
       [-0.88640526,  1.23079873,  0.70384427, -0.59008772],
       [-0.88640526, -0.70690189,  0.70384427,  1.27334719],
       [ 1.12815215, -1.42456879,  0.78018313, -1.75473454],
       [-0.88640526, -0.56336851,  0.78018313,  1.6615628 ],
       [ 1.12815215,  0.80019859,  0.93286085, -0.93948177],
       [-0.88640526, -0.20453507,  0.93286085,  0.96277471],
       [ 1.12815215,  0.22606507,  0.97103028, -1.17241113],
       [-0.88640526, -0.41983513,  0.97103028,  1.73920592],
       [-0.88640526, -0.20453507,  1.00919971, -0.90066021],
       [ 1.12815215, -0.49160182,  1.00919971,  0.49691598],
       [ 1.12815215,  0.08253169,  1.00919971, -1.44416206],
       [ 1.12815215, -0.77866858,  1.00919971,  0.96277471],
       [ 1.12815215, -0.20453507,  1.00919971, -1.56062674],
       [ 1.12815215, -0.20453507,  1.00919971,  1.62274124],
       [-0.88640526,  0.94373197,  1.04736914, -1.44416206],
       [-0.88640526, -0.6351352 ,  1.04736914,  1.38981187],
       [ 1.12815215,  1.37433211,  1.04736914, -1.36651894],
       [ 1.12815215, -0.85043527,  1.04736914,  0.72984534],
       [ 1.12815215,  1.4460988 ,  1.23821628, -1.4053405 ],
       [ 1.12815215, -0.27630176,  1.23821628,  1.54509812],
       [-0.88640526, -0.13276838,  1.390894  , -0.7065524 ],
       [-0.88640526, -0.49160182,  1.390894  ,  1.38981187],
       [ 1.12815215,  0.51313183,  1.42906343, -1.36651894],
       [-0.88640526, -0.70690189,  1.42906343,  1.46745499],
       [-0.88640526,  0.15429838,  1.46723286, -0.43480148],
       [ 1.12815215, -0.6351352 ,  1.46723286,  1.81684904],
       [-0.88640526,  1.08726535,  1.54357172, -1.01712489],
       [ 1.12815215, -0.77866858,  1.54357172,  0.69102378],
       [-0.88640526,  0.15429838,  1.61991057, -1.28887582],
       [-0.88640526, -0.20453507,  1.61991057,  1.35099031],
       [-0.88640526, -0.34806844,  1.61991057, -1.05594645],
       [-0.88640526, -0.49160182,  1.61991057,  0.72984534],
       [ 1.12815215, -0.41983513,  2.00160487, -1.63826986],
       [-0.88640526, -0.06100169,  2.00160487,  1.58391968],
       [-0.88640526,  0.58489852,  2.26879087, -1.32769738],
       [-0.88640526, -0.27630176,  2.26879087,  1.11806095],
       [-0.88640526,  0.44136514,  2.49780745, -0.86183865],
       [ 1.12815215, -0.49160182,  2.49780745,  0.92395314],
       [ 1.12815215, -0.49160182,  2.91767117, -1.25005425],
       [ 1.12815215, -0.6351352 ,  2.91767117,  1.27334719]])

**model1 : methode 'forgy',k=5**

In [8]:
model1 = KMeans(k=5,random_state=42)

In [9]:
model1.fit(X)

Itération 1/100 | Écart : 1.5440 | Stable : 0/5
Itération 2/100 | Écart : 0.3635 | Stable : 0/5
Itération 3/100 | Écart : 0.1865 | Stable : 0/5
Itération 4/100 | Écart : 0.0950 | Stable : 0/5
Itération 5/100 | Écart : 0.0979 | Stable : 0/5
Itération 6/100 | Écart : 0.0636 | Stable : 0/5
Itération 7/100 | Écart : 0.0981 | Stable : 0/5
Itération 8/100 | Écart : 0.2062 | Stable : 0/5
Itération 9/100 | Écart : 0.2099 | Stable : 0/5
Itération 10/100 | Écart : 0.0469 | Stable : 0/5
Itération 11/100 | Écart : 0.0393 | Stable : 0/5
Itération 12/100 | Écart : 0.0000 | Stable : 0/5
Itération 13/100 | Écart : 0.0000 | Stable : 1/5
Itération 14/100 | Écart : 0.0000 | Stable : 2/5
Itération 15/100 | Écart : 0.0000 | Stable : 3/5
Itération 16/100 | Écart : 0.0000 | Stable : 4/5
Itération 17/100 | Écart : 0.0000 | Stable : 5/5

 Entraînement terminé — convergence en 17 itération(s)

In [10]:
print(model1.calculate_silhouette_score(X))
print(silhouette_score(X,model1.labels))

0.2775683118896831
0.2775683118896831

**model2 : methode 'random_partition',k=2**

In [11]:
model2 = KMeans(k=5,init_method = 'random_partition',random_state=42)
model2.fit(X)

Itération 1/100 | Écart : 1.4458 | Stable : 0/5
Itération 2/100 | Écart : 0.5958 | Stable : 0/5
Itération 3/100 | Écart : 0.1659 | Stable : 0/5
Itération 4/100 | Écart : 0.1276 | Stable : 0/5
Itération 5/100 | Écart : 0.1257 | Stable : 0/5
Itération 6/100 | Écart : 0.1975 | Stable : 0/5
Itération 7/100 | Écart : 0.2282 | Stable : 0/5
Itération 8/100 | Écart : 0.1627 | Stable : 0/5
Itération 9/100 | Écart : 0.1438 | Stable : 0/5
Itération 10/100 | Écart : 0.1753 | Stable : 0/5
Itération 11/100 | Écart : 0.1409 | Stable : 0/5
Itération 12/100 | Écart : 0.0843 | Stable : 0/5
Itération 13/100 | Écart : 0.0713 | Stable : 0/5
Itération 14/100 | Écart : 0.0419 | Stable : 0/5
Itération 15/100 | Écart : 0.0428 | Stable : 0/5
Itération 16/100 | Écart : 0.0000 | Stable : 0/5
Itération 17/100 | Écart : 0.0000 | Stable : 1/5
Itération 18/100 | Écart : 0.0000 | Stable : 2/5
Itération 19/100 | Écart : 0.0000 | Stable : 3/5
Itération 20/100 | Écart : 0.0000 | Stable : 4/5
Itération 21/100 | Écart : 0.0000 | Stable : 5/5

 Entraînement terminé — convergence en 21 itération(s)

In [12]:
print(model2.calculate_silhouette_score(X))
print(silhouette_score(X,model2.labels))

0.2891171435319872
0.2891171435319872

**model3 : methode 'kmeans++',k=2**

In [13]:
model3 = KMeans(k=5,init_method = 'kmeans++',random_state=42)
model3.fit(X)

Itération 1/100 | Écart : 1.2177 | Stable : 0/5
Itération 2/100 | Écart : 0.4146 | Stable : 0/5
Itération 3/100 | Écart : 0.2969 | Stable : 0/5
Itération 4/100 | Écart : 0.0491 | Stable : 0/5
Itération 5/100 | Écart : 0.0333 | Stable : 0/5
Itération 6/100 | Écart : 0.0349 | Stable : 0/5
Itération 7/100 | Écart : 0.0591 | Stable : 0/5
Itération 8/100 | Écart : 0.0385 | Stable : 0/5
Itération 9/100 | Écart : 0.0573 | Stable : 0/5
Itération 10/100 | Écart : 0.0883 | Stable : 0/5
Itération 11/100 | Écart : 0.0313 | Stable : 0/5
Itération 12/100 | Écart : 0.0568 | Stable : 0/5
Itération 13/100 | Écart : 0.0581 | Stable : 0/5
Itération 14/100 | Écart : 0.0574 | Stable : 0/5
Itération 15/100 | Écart : 0.0514 | Stable : 0/5
Itération 16/100 | Écart : 0.0000 | Stable : 0/5
Itération 17/100 | Écart : 0.0000 | Stable : 1/5
Itération 18/100 | Écart : 0.0000 | Stable : 2/5
Itération 19/100 | Écart : 0.0000 | Stable : 3/5
Itération 20/100 | Écart : 0.0000 | Stable : 4/5
Itération 21/100 | Écart : 0.0000 | Stable : 5/5

 Entraînement terminé — convergence en 21 itération(s)

In [14]:
print(model3.calculate_silhouette_score(X))
print(silhouette_score(X,model3.labels))

0.26507184956807267
0.26507184956807267

In [15]:
print(f"Forgy          : {model1.calculate_silhouette_score(X):.4f}")
print(f"Random partition: {model2.calculate_silhouette_score(X):.4f}")
print(f"KMeans++       : {model3.calculate_silhouette_score(X):.4f}")

Forgy          : 0.2776
Random partition: 0.2891
KMeans++       : 0.2651

**KMeans de scikit-learn**

In [16]:
from sklearn.cluster import KMeans as KM

In [17]:
model4 = KM(n_clusters = 5,random_state=42)

In [18]:
model4.fit(X)

KMeans(n_clusters=5, random_state=42)

In [19]:
model4.labels_

array([2, 2, 4, 4, 4, 4, 4, 4, 0, 4, 0, 4, 0, 4, 0, 2, 4, 2, 0, 4, 2, 2,
       0, 2, 0, 2, 0, 2, 4, 4, 0, 4, 0, 2, 0, 4, 0, 4, 4, 4, 0, 2, 0, 4,
       0, 4, 0, 4, 4, 4, 0, 2, 4, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 0, 2,
       4, 0, 2, 4, 0, 0, 0, 0, 0, 2, 3, 2, 4, 0, 0, 2, 0, 3, 4, 0, 0, 4,
       4, 0, 0, 2, 0, 3, 4, 2, 3, 4, 0, 2, 4, 3, 0, 2, 0, 4, 0, 0, 0, 0,
       0, 4, 3, 2, 4, 4, 0, 3, 3, 3, 2, 3, 3, 2, 3, 3, 1, 2, 1, 2, 1, 2,
       3, 3, 1, 3, 3, 2, 1, 3, 0, 2, 3, 3, 1, 2, 1, 3, 3, 2, 1, 2, 3, 3,
       3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 1, 3, 1, 3, 3, 2, 1, 2, 1, 2, 3, 3,
       1, 2, 1, 2, 3, 3, 1, 3, 3, 2, 3, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 2,
       1, 2], dtype=int32)

In [20]:
print(silhouette_score(X,model4.labels_))

0.27191023466188324